name: CI-CD

on:
  push:
    branches: ["**"]  # Trigger on all branches
  pull_request:
    branches: [ main ]

jobs:
  # ðŸ”¹ CI Job - Use existing CI workflow
  ci:
    uses: ./.github/workflows/ci-flow.yml
    secrets: inherit  # âœ… sends secrets to reusable workflow

  # ðŸ”¹ CD Job - Use existing CD workflow
  #   Executed if CI is successful
  cd:
    needs: ci  # âœ… Wait from CI to finish
    uses: ./.github/workflows/cd-flow.yml
    secrets: inherit  # âœ… Sends secrets to reusable workflow
